name: Docker CI

on:
  push:
    branches: [master]

jobs:
  build:
    env:
      DOCKER_HUB_USER: dewkul
      DOCKER_HUB_REPO: inv-u-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get datetime tag
        run: echo "NOW=$(date +'%y%m%d.%H%M')" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          # platforms: linux/amd64,linux/arm
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_REPO }}:latest
            ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_HUB_REPO }}:${{ env.NOW }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
